version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
  apt_packages:
    - libisal-dev
  jobs:
    pre_build:
      - git submodule update --init --recursive
      - make -C src doc

sphinx:
  configuration: docs/conf.py
