name: Publish release on tag creation

on:
  push:
    tags:
      - '*'

jobs:
  package:
    name: Packge source and dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get shortened version of release tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Package source code
        shell: bash
        run: |
          tar -cvf humid-${{ env.RELEASE_VERSION }}.tar lib/ src/

      - name: Print event context
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT

      - name: Upload archive as artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-tar
          path: humid-${{ env.RELEASE_VERSION}}.tar

  release:
      name: Create a release out of the tar archive
      needs: package
      runs-on: ubuntu-latest
      steps:
        - name: Get shortened version of release tag
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

        - name: Download package result
          uses: actions/download-artifact@v3
          with:
            name: release-tar

        - name: Create release
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            gh release create ${{ env.RELEASE_VERSION}} --generate-notes humid-${{ env.RELEASE_VERSION}}.tar
